# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 587)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LanguageBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LanguageBox.sizePolicy().hasHeightForWidth())
        self.LanguageBox.setSizePolicy(sizePolicy)
        self.LanguageBox.setObjectName("LanguageBox")
        # Add icons for languages (ensure you have these resources)
        self.LanguageBox.setStyleSheet("""
            QComboBox {
                border: 1.5px solid #C62828;
                border-radius: 12px;
                padding: 4px 24px 4px 8px;
                min-width: 60px;
                font-weight: bold;
                background: #fff;
            }
            QComboBox::drop-down {
                border-left: 1.5px solid #C62828;
                width: 24px;
            }
            QComboBox::down-arrow {
                image: url(:/images/down-arrow.png);
                width: 18px;
                height: 18px;
            }
            QComboBox QAbstractItemView {
                border: 1px solid #C62828;
                selection-background-color: #fbe9e7;
            }
        """)
        self.gridLayout_2.addWidget(self.LanguageBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.collectionButton = QtWidgets.QPushButton(Form)
        self.collectionButton.setObjectName("collectionButton")
        self.verticalLayout_2.addWidget(self.collectionButton)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.HieuUngButton = QtWidgets.QPushButton(Form)
        self.HieuUngButton.setObjectName("HieuUngButton")
        self.verticalLayout_2.addWidget(self.HieuUngButton)
        self.ThemButton = QtWidgets.QPushButton(Form)
        self.ThemButton.setObjectName("ThemButton")
        self.verticalLayout_2.addWidget(self.ThemButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BVSTDButton = QtWidgets.QPushButton(Form)
        self.BVSTDButton.setObjectName("BVSTDButton")
        self.verticalLayout.addWidget(self.BVSTDButton)
        self.TCQCButton = QtWidgets.QPushButton(Form)
        self.TCQCButton.setObjectName("TCQCButton")
        self.verticalLayout.addWidget(self.TCQCButton)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        Form.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828;
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #FF3366; /* Default color */
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 16px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:checked {
                background-color: #C62828; /* Checked color */
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # After creating all your buttons in setupUi:
        self.collectionButton.setCheckable(True)
        self.pushButton.setCheckable(True)
        self.HieuUngButton.setCheckable(True)
        self.ThemButton.setCheckable(True)
        self.BVSTDButton.setCheckable(True)
        self.TCQCButton.setCheckable(True)

        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setExclusive(True)
        self.buttonGroup.addButton(self.collectionButton)
        self.buttonGroup.addButton(self.pushButton)
        self.buttonGroup.addButton(self.HieuUngButton)
        self.buttonGroup.addButton(self.ThemButton)
        self.buttonGroup.addButton(self.BVSTDButton)
        self.buttonGroup.addButton(self.TCQCButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "THÔNG TIN"))
        self.collectionButton.setText(_translate("Form", "COLLECTION"))
        self.pushButton.setText(_translate("Form", "MÀU"))
        self.HieuUngButton.setText(_translate("Form", "HIỆU ỨNG"))
        self.ThemButton.setText(_translate("Form", "THÊM / CẬP NHẬT"))
        self.BVSTDButton.setText(_translate("Form", "BẢN VẼ STD"))
        self.TCQCButton.setText(_translate("Form", "TIÊU CHUẨN QC"))
import resources_rc
