# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCKiemtraDialog_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TCDialog(object):
    def setupUi(self, TCDialog):
        TCDialog.setObjectName("TCDialog")
        TCDialog.resize(1146, 815)
        self.gridLayout = QtWidgets.QGridLayout(TCDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(TCDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(TCDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(TCDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(TCDialog)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.label_2 = QtWidgets.QLabel(TCDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(TCDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.exportexcelButton = QtWidgets.QPushButton(TCDialog)
        self.exportexcelButton.setObjectName("exportexcelButton")
        self.horizontalLayout_2.addWidget(self.exportexcelButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(TCDialog)
        self.tableView.setObjectName("tableView")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setStyleSheet("""
            QTableView {
                background: #fff;
                alternate-background-color: #e3eafc;
                selection-background-color: #4567B7;
                selection-color: #fff;
                font-size: 14px;
                gridline-color: #4567B7;
            }
            QHeaderView::section {
                background-color: #4567B7;
                color: white;
                font-weight: bold;
                font-size: 14px;
                border: 1px solid #fff;
            }
        """)
        self.horizontalLayout.addWidget(self.tableView)
        self.imageLabel = QtWidgets.QLabel(TCDialog)
        self.imageLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        TCDialog.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828; /* Strong red for main label */
                font-weight: bold;
            }
            QPushButton {
                background-color: #FF3366;
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 16px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:pressed {
                background-color: #C62828; /* Clicked color */
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(TCDialog)
        QtCore.QMetaObject.connectSlotsByName(TCDialog)

    def retranslateUi(self, TCDialog):
        _translate = QtCore.QCoreApplication.translate
        TCDialog.setWindowTitle(_translate("TCDialog", "Dialog"))
        self.label.setText(_translate("TCDialog", "PO"))
        self.label_3.setText(_translate("TCDialog", "SUPPLIER"))
        self.label_2.setText(_translate("TCDialog", "PRODUCT NAME"))
        self.exportexcelButton.setText(_translate("TCDialog", "XUẤT EXCEL"))
        self.imageLabel.setText(_translate("TCDialog", "This is space to show defect image"))
