# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WH_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WHForm(object):
    def setupUi(self, WHForm):
        WHForm.setObjectName("WHForm")
        WHForm.resize(1075, 850)
        self.gridLayout = QtWidgets.QGridLayout(WHForm)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(WHForm)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.exportexcelButton = QtWidgets.QPushButton(WHForm)
        self.exportexcelButton.setObjectName("exportexcelButton")
        self.gridLayout.addWidget(self.exportexcelButton, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateEdit = QtWidgets.QDateEdit(WHForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.filterButton = QtWidgets.QPushButton(WHForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterButton.sizePolicy().hasHeightForWidth())
        self.filterButton.setSizePolicy(sizePolicy)
        self.filterButton.setObjectName("filterButton")
        self.horizontalLayout_2.addWidget(self.filterButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(WHForm)
        self.tableView.setObjectName("tableView")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setStyleSheet("""
            QTableView {
                background: #fff;
                alternate-background-color: #fbe9e7;
                selection-background-color: #ffcdd2;
                selection-color: #b71c1c;
                font-size: 14px;
                gridline-color: #C62828;
            }
            QHeaderView::section {
                background-color: #C62828;
                color: white;
                font-weight: bold;
                font-size: 14px;
                border: 1px solid #fff;
            }
        """)
        self.gridLayout.addWidget(self.tableView, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.viewcrateButton = QtWidgets.QPushButton(WHForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewcrateButton.sizePolicy().hasHeightForWidth())
        self.viewcrateButton.setSizePolicy(sizePolicy)
        self.viewcrateButton.setObjectName("viewcrateButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.viewcrateButton)
        self.viewSKUButton = QtWidgets.QPushButton(WHForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewSKUButton.sizePolicy().hasHeightForWidth())
        self.viewSKUButton.setSizePolicy(sizePolicy)
        self.viewSKUButton.setObjectName("viewSKUButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.viewSKUButton)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NXTButton = QtWidgets.QPushButton(WHForm)
        self.NXTButton.setObjectName("NXTButton")
        self.horizontalLayout.addWidget(self.NXTButton)
        self.nhapButton = QtWidgets.QPushButton(WHForm)
        self.nhapButton.setObjectName("nhapButton")
        self.horizontalLayout.addWidget(self.nhapButton)
        self.xuatButton = QtWidgets.QPushButton(WHForm)
        self.xuatButton.setObjectName("xuatButton")
        self.horizontalLayout.addWidget(self.xuatButton)
        self.theodoiairButton = QtWidgets.QPushButton(WHForm)
        self.theodoiairButton.setObjectName("theodoiairButton")
        self.horizontalLayout.addWidget(self.theodoiairButton)
        self.LLCsampleButton = QtWidgets.QPushButton(WHForm)
        self.LLCsampleButton.setObjectName("LLCsampleButton")
        self.horizontalLayout.addWidget(self.LLCsampleButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.inputdataButton = QtWidgets.QPushButton(WHForm)
        self.inputdataButton.setObjectName("inputdataButton")
        self.gridLayout.addWidget(self.inputdataButton, 1, 1, 1, 1)
        WHForm.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828;
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #FF3366; /* Default color */
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 16px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:checked {
                background-color: #C62828; /* Checked color */
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(WHForm)
        QtCore.QMetaObject.connectSlotsByName(WHForm)

    def retranslateUi(self, WHForm):
        _translate = QtCore.QCoreApplication.translate
        WHForm.setWindowTitle(_translate("WHForm", "Form"))
        self.exportexcelButton.setText(_translate("WHForm", "EXPORT EXCEL"))
        self.filterButton.setText(_translate("WHForm", "FILTER"))
        self.viewcrateButton.setText(_translate("WHForm", "VIEW CRATE"))
        self.viewSKUButton.setText(_translate("WHForm", "VIEW SKU"))
        self.NXTButton.setText(_translate("WHForm", "TỔNG THỂ"))
        self.nhapButton.setText(_translate("WHForm", "NHẬP"))
        self.xuatButton.setText(_translate("WHForm", "XUẤT"))
        self.theodoiairButton.setText(_translate("WHForm", "THEO DÕI HÀNG AIR"))
        self.LLCsampleButton.setText(_translate("WHForm", "LLC SAMPLE"))
        self.inputdataButton.setText(_translate("WHForm", "NHẬP DATA"))
import resources_rc
