# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ColorwayDialog_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorwayDialog(object):
    def setupUi(self, ColorwayDialog):
        ColorwayDialog.setObjectName("ColorwayDialog")
        ColorwayDialog.resize(579, 244)
        self.gridLayout = QtWidgets.QGridLayout(ColorwayDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ColorwayDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listView = QtWidgets.QListView(ColorwayDialog)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.okButton = QtWidgets.QPushButton(ColorwayDialog)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(ColorwayDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)

        self.retranslateUi(ColorwayDialog)
        QtCore.QMetaObject.connectSlotsByName(ColorwayDialog)

    def retranslateUi(self, ColorwayDialog):
        _translate = QtCore.QCoreApplication.translate
        ColorwayDialog.setWindowTitle(_translate("ColorwayDialog", "COLORWAY SEARCH"))
        self.label.setText(_translate("ColorwayDialog", "RENDER COLOUR WAY"))
        self.okButton.setText(_translate("ColorwayDialog", "OK"))
        self.cancelButton.setText(_translate("ColorwayDialog", "CANCEL"))
