# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defectlist_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DefectListWidget(object):
    def setupUi(self, DefectListWidget):
        DefectListWidget.setObjectName("DefectListWidget")
        DefectListWidget.resize(1034, 794)
        self.gridLayout = QtWidgets.QGridLayout(DefectListWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.defectaddopenButton = QtWidgets.QPushButton(DefectListWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defectaddopenButton.sizePolicy().hasHeightForWidth())
        self.defectaddopenButton.setSizePolicy(sizePolicy)
        self.defectaddopenButton.setObjectName("defectaddopenButton")
        self.gridLayout.addWidget(self.defectaddopenButton, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(DefectListWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        DefectListWidget.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828;
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #FF3366; /* Default color */
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 12px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:checked {
                background-color: #C62828; /* Checked color */
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(DefectListWidget)
        QtCore.QMetaObject.connectSlotsByName(DefectListWidget)

    def retranslateUi(self, DefectListWidget):
        _translate = QtCore.QCoreApplication.translate
        DefectListWidget.setWindowTitle(_translate("DefectListWidget", "DEFECTS LIST"))
        self.defectaddopenButton.setText(_translate("DefectListWidget", "THÊM"))
