# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printchecksheet_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintChecksheetDialog(object):
    def setupUi(self, PrintChecksheetDialog):
        PrintChecksheetDialog.setObjectName("PrintChecksheetDialog")
        PrintChecksheetDialog.resize(1006, 713)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PrintChecksheetDialog.sizePolicy().hasHeightForWidth())
        PrintChecksheetDialog.setSizePolicy(sizePolicy)
        PrintChecksheetDialog.setMinimumSize(QtCore.QSize(0, 41))
        PrintChecksheetDialog.setStyleSheet("    QWidget {\n"
"                background: white;\n"
"            }\n"
"            QLabel {\n"
"                color: #C62828;\n"
"                font-weight: bold;\n"
"            }\n"
"            QLineEdit, QTextEdit {\n"
"                border: 1.5px solid black;\n"
"                border-radius: 4px;\n"
"                background: #fff;\n"
"                padding: 4px;\n"
"            }\n"
"            QPushButton {\n"
"                background-color: #FF3366; /* Default color */\n"
"                color: white;\n"
"                border: 1.5px solid #C62828;\n"
"                border-radius: 12px;\n"
"                padding: 6px 12px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:checked {\n"
"                background-color: #C62828; /* Checked color */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #b71c1c;\n"
"            }")
        self.gridLayout = QtWidgets.QGridLayout(PrintChecksheetDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.exportexcel = QtWidgets.QPushButton(PrintChecksheetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportexcel.sizePolicy().hasHeightForWidth())
        self.exportexcel.setSizePolicy(sizePolicy)
        self.exportexcel.setObjectName("exportexcel")
        self.gridLayout.addWidget(self.exportexcel, 0, 0, 1, 1)
        self.selectallbutton = QtWidgets.QPushButton(PrintChecksheetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectallbutton.sizePolicy().hasHeightForWidth())
        self.selectallbutton.setSizePolicy(sizePolicy)
        self.selectallbutton.setMinimumSize(QtCore.QSize(101, 32))
        self.selectallbutton.setMaximumSize(QtCore.QSize(101, 16777215))
        self.selectallbutton.setObjectName("selectallbutton")
        self.gridLayout.addWidget(self.selectallbutton, 0, 1, 1, 1)
        self.unselectallbutton = QtWidgets.QPushButton(PrintChecksheetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unselectallbutton.sizePolicy().hasHeightForWidth())
        self.unselectallbutton.setSizePolicy(sizePolicy)
        self.unselectallbutton.setMinimumSize(QtCore.QSize(110, 32))
        self.unselectallbutton.setMaximumSize(QtCore.QSize(101, 16777215))
        self.unselectallbutton.setObjectName("unselectallbutton")
        self.gridLayout.addWidget(self.unselectallbutton, 0, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(PrintChecksheetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(104, 35))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 3, 1, 1)
        self.widget = QtWidgets.QWidget(PrintChecksheetDialog)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(PrintChecksheetDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 55))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 5)
        self.tableView = QtWidgets.QTableView(PrintChecksheetDialog)
        self.tableView.setMinimumSize(QtCore.QSize(981, 591))
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 5)

        self.retranslateUi(PrintChecksheetDialog)
        QtCore.QMetaObject.connectSlotsByName(PrintChecksheetDialog)

    def retranslateUi(self, PrintChecksheetDialog):
        _translate = QtCore.QCoreApplication.translate
        PrintChecksheetDialog.setWindowTitle(_translate("PrintChecksheetDialog", "Dialog"))
        self.exportexcel.setText(_translate("PrintChecksheetDialog", "In"))
        self.selectallbutton.setText(_translate("PrintChecksheetDialog", "Select All"))
        self.unselectallbutton.setText(_translate("PrintChecksheetDialog", "UnSelect All"))
        self.textEdit.setHtml(_translate("PrintChecksheetDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400;\"><br /></p></body></html>"))
        self.groupBox.setTitle(_translate("PrintChecksheetDialog", "Selected Sheet"))
