# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printchecksheet_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintChecksheetDialog(object):
    def setupUi(self, PrintChecksheetDialog):
        PrintChecksheetDialog.setObjectName("PrintChecksheetDialog")
        PrintChecksheetDialog.resize(1006, 713)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PrintChecksheetDialog.sizePolicy().hasHeightForWidth())
        PrintChecksheetDialog.setSizePolicy(sizePolicy)
        PrintChecksheetDialog.setMinimumSize(QtCore.QSize(0, 41))
        PrintChecksheetDialog.setStyleSheet("    QWidget {\n"
"                background: white;\n"
"            }\n"
"            QLabel {\n"
"                color: #C62828;\n"
"                font-weight: bold;\n"
"            }\n"
"            QLineEdit, QTextEdit {\n"
"                border: 1.5px solid black;\n"
"                border-radius: 4px;\n"
"                background: #fff;\n"
"                padding: 4px;\n"
"            }\n"
"            QPushButton {\n"
"                background-color: #FF3366; /* Default color */\n"
"                color: white;\n"
"                border: 1.5px solid #C62828;\n"
"                border-radius: 12px;\n"
"                padding: 6px 12px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:checked {\n"
"                background-color: #C62828; /* Checked color */\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #b71c1c;\n"
"            }")
        self.gridLayout = QtWidgets.QGridLayout(PrintChecksheetDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.exportexcel = QtWidgets.QPushButton(PrintChecksheetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportexcel.sizePolicy().hasHeightForWidth())
        self.exportexcel.setSizePolicy(sizePolicy)
        self.exportexcel.setObjectName("exportexcel")
        self.gridLayout.addWidget(self.exportexcel, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(PrintChecksheetDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 55))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(PrintChecksheetDialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 1)

        self.retranslateUi(PrintChecksheetDialog)
        QtCore.QMetaObject.connectSlotsByName(PrintChecksheetDialog)

    def retranslateUi(self, PrintChecksheetDialog):
        _translate = QtCore.QCoreApplication.translate
        PrintChecksheetDialog.setWindowTitle(_translate("PrintChecksheetDialog", "Dialog"))
        self.exportexcel.setText(_translate("PrintChecksheetDialog", "In"))
        self.groupBox.setTitle(_translate("PrintChecksheetDialog", "Selected Sheet"))
