# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(453, 276)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QCappButton = QtWidgets.QPushButton(self.centralwidget)
        self.QCappButton.setObjectName("QCappButton")
        self.horizontalLayout.addWidget(self.QCappButton)
        self.WHappButton = QtWidgets.QPushButton(self.centralwidget)
        self.WHappButton.setObjectName("WHappButton")
        self.horizontalLayout.addWidget(self.WHappButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.LanguageBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LanguageBox.sizePolicy().hasHeightForWidth())
        self.LanguageBox.setSizePolicy(sizePolicy)
        self.LanguageBox.setObjectName("LanguageBox")
        self.LanguageBox.setStyleSheet("""
            QComboBox {
                border: 1.5px solid #C62828;
                border-radius: 12px;
                padding: 4px 24px 4px 8px;
                min-width: 60px;
                font-weight: bold;
                background: #fff;
            }
            QComboBox::drop-down {
                border-left: 1.5px solid #C62828;
                width: 24px;
            }
            QComboBox::down-arrow {
                image: url(:/images/down-arrow.png);
                width: 18px;
                height: 18px;
            }
            QComboBox QAbstractItemView {
                border: 1px solid #C62828;
                selection-background-color: #fbe9e7;
            }
        """)
        self.gridLayout.addWidget(self.LanguageBox, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        StartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 26))
        self.menubar.setObjectName("menubar")
        StartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)
        StartWindow.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828;
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #FF3366; /* Default color */
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 12px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:checked {
                background-color: #C62828; /* Checked color */
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "MainWindow"))
        self.QCappButton.setText(_translate("StartWindow", "QUALITY CONTROL"))
        self.WHappButton.setText(_translate("StartWindow", "WAREHOUSE"))
        self.label_2.setText(_translate("StartWindow", "Developed by Le Tuan Anh"))
import resources_rc
