# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WH_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WHForm(object):
    def setupUi(self, WHForm):
        WHForm.setObjectName("WHForm")
        WHForm.resize(1177, 850)
        self.gridLayout_2 = QtWidgets.QGridLayout(WHForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.viewcrateButton = QtWidgets.QPushButton(WHForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewcrateButton.sizePolicy().hasHeightForWidth())
        self.viewcrateButton.setSizePolicy(sizePolicy)
        self.viewcrateButton.setObjectName("viewcrateButton")
        self.verticalLayout_2.addWidget(self.viewcrateButton)
        self.viewSKUButton = QtWidgets.QPushButton(WHForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewSKUButton.sizePolicy().hasHeightForWidth())
        self.viewSKUButton.setSizePolicy(sizePolicy)
        self.viewSKUButton.setObjectName("viewSKUButton")
        self.verticalLayout_2.addWidget(self.viewSKUButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(WHForm)
        self.label_2.setMaximumSize(QtCore.QSize(124, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(WHForm)
        self.label_3.setMaximumSize(QtCore.QSize(124, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(WHForm)
        self.label_4.setMaximumSize(QtCore.QSize(124, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(WHForm)
        self.label_5.setMaximumSize(QtCore.QSize(124, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(WHForm)
        self.label_6.setMaximumSize(QtCore.QSize(124, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(WHForm)
        self.label_7.setMaximumSize(QtCore.QSize(124, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 5, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(WHForm)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(124, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(WHForm)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(124, 40))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(WHForm)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(124, 40))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(WHForm)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(124, 40))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(WHForm)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(124, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(WHForm)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(124, 40))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(124, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputdataButton = QtWidgets.QPushButton(WHForm)
        self.inputdataButton.setMinimumSize(QtCore.QSize(161, 30))
        self.inputdataButton.setObjectName("inputdataButton")
        self.verticalLayout.addWidget(self.inputdataButton)
        self.exportexcelButton = QtWidgets.QPushButton(WHForm)
        self.exportexcelButton.setMinimumSize(QtCore.QSize(161, 30))
        self.exportexcelButton.setObjectName("exportexcelButton")
        self.verticalLayout.addWidget(self.exportexcelButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(WHForm)
        self.tableView.setMinimumSize(QtCore.QSize(1147, 611))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setStyleSheet("""
            QTableView {
                background: #fff;
                alternate-background-color: #fbe9e7;
                selection-background-color: #ffcdd2;
                selection-color: #b71c1c;
                font-size: 14px;
                gridline-color: #C62828;
            }
            QHeaderView::section {
                background-color: #C62828;
                color: white;
                font-weight: bold;
                font-size: 14px;
                border: 1px solid #fff;
            }
        """)
        self.gridLayout_2.addWidget(self.tableView, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(WHForm)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NXTButton = QtWidgets.QPushButton(WHForm)
        self.NXTButton.setObjectName("NXTButton")
        self.horizontalLayout.addWidget(self.NXTButton)
        self.nhapButton = QtWidgets.QPushButton(WHForm)
        self.nhapButton.setObjectName("nhapButton")
        self.horizontalLayout.addWidget(self.nhapButton)
        self.xuatButton = QtWidgets.QPushButton(WHForm)
        self.xuatButton.setObjectName("xuatButton")
        self.horizontalLayout.addWidget(self.xuatButton)
        self.theodoiairButton = QtWidgets.QPushButton(WHForm)
        self.theodoiairButton.setObjectName("theodoiairButton")
        self.horizontalLayout.addWidget(self.theodoiairButton)
        self.LLCsampleButton = QtWidgets.QPushButton(WHForm)
        self.LLCsampleButton.setObjectName("LLCsampleButton")
        self.horizontalLayout.addWidget(self.LLCsampleButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        WHForm.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828;
                font-weight: bold;
            }
            QLineEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
                font-size: 18px;
                font-weight: bold;
            }
            QPushButton {
                background-color: #FF3366; /* Default color */
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 12px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:checked {
                background-color: #C62828; /* Checked color */
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
            QDateEdit {
                border: 1.0px solid black;
                border-radius: 6px;
                padding: 4px 8px;
                background: #fff;
                font-weight: bold;
                color: #333;
                min-width: 120px;
            }
            QDateEdit::drop-down {
                subcontrol-origin: padding;
                subcontrol-position: top right;
                width: 24px;
                border-left-width: 1px;
                border-left-color: #C62828;
                border-left-style: solid;
                border-top-right-radius: 6px;
                border-bottom-right-radius: 6px;
            }
        """)
        self.retranslateUi(WHForm)
        QtCore.QMetaObject.connectSlotsByName(WHForm)

    def retranslateUi(self, WHForm):
        _translate = QtCore.QCoreApplication.translate
        WHForm.setWindowTitle(_translate("WHForm", "Form"))
        self.viewcrateButton.setText(_translate("WHForm", "VIEW ORIGINAL"))
        self.viewSKUButton.setText(_translate("WHForm", "VIEW SKU"))
        self.label_2.setText(_translate("WHForm", "NHẬP"))
        self.label_3.setText(_translate("WHForm", "XUẤT"))
        self.label_4.setText(_translate("WHForm", "TỒN KNQ"))
        self.label_5.setText(_translate("WHForm", "ALLOCATED"))
        self.label_6.setText(_translate("WHForm", "TỒN CUỐI"))
        self.label_7.setText(_translate("WHForm", "QTY"))
        self.inputdataButton.setText(_translate("WHForm", "NHẬP DATA"))
        self.exportexcelButton.setText(_translate("WHForm", "EXPORT EXCEL"))
        self.NXTButton.setText(_translate("WHForm", "TỔNG THỂ"))
        self.nhapButton.setText(_translate("WHForm", "NHẬP"))
        self.xuatButton.setText(_translate("WHForm", "XUẤT"))
        self.theodoiairButton.setText(_translate("WHForm", "THEO DÕI HÀNG AIR"))
        self.LLCsampleButton.setText(_translate("WHForm", "LLC SAMPLE"))
import resources_rc
