# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ColorwayDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ColorwayDialog(object):
    def setupUi(self, ColorwayDialog):
        ColorwayDialog.setObjectName("ColorwayDialog")
        ColorwayDialog.resize(599, 269)
        self.gridLayout_2 = QtWidgets.QGridLayout(ColorwayDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(ColorwayDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.listView = QtWidgets.QListView(ColorwayDialog)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.okButton = QtWidgets.QPushButton(ColorwayDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(ColorwayDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        ColorwayDialog.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828; /* Strong red for main label */
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #C62828;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(ColorwayDialog)
        QtCore.QMetaObject.connectSlotsByName(ColorwayDialog)

    def retranslateUi(self, ColorwayDialog):
        _translate = QtCore.QCoreApplication.translate
        ColorwayDialog.setWindowTitle(_translate("ColorwayDialog", "Colorway Search"))
        self.label.setText(_translate("ColorwayDialog", "Color way Render"))
        self.okButton.setText(_translate("ColorwayDialog", "OK"))
        self.cancelButton.setText(_translate("ColorwayDialog", "Cancel"))
