# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCKiemtraDialog_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TCDialog(object):
    def setupUi(self, TCDialog):
        TCDialog.setObjectName("TCDialog")
        TCDialog.resize(857, 559)
        self.gridLayout_2 = QtWidgets.QGridLayout(TCDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(TCDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(TCDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(TCDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(TCDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.exportexcelButton = QtWidgets.QPushButton(TCDialog)
        self.exportexcelButton.setObjectName("exportexcelButton")
        self.horizontalLayout_2.addWidget(self.exportexcelButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(TCDialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.imageLabel = QtWidgets.QLabel(TCDialog)
        self.imageLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(TCDialog)
        QtCore.QMetaObject.connectSlotsByName(TCDialog)

    def retranslateUi(self, TCDialog):
        _translate = QtCore.QCoreApplication.translate
        TCDialog.setWindowTitle(_translate("TCDialog", "Dialog"))
        self.label.setText(_translate("TCDialog", "PO"))
        self.label_2.setText(_translate("TCDialog", "Product Name"))
        self.exportexcelButton.setText(_translate("TCDialog", "Export excel"))
        self.imageLabel.setText(_translate("TCDialog", "This is space to show defect image"))
