# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bvstd_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(613, 412)
        Dialog.setWindowOpacity(1.0)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(Dialog)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.gridLayout.addWidget(self.searchLineEdit, 0, 0, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(Dialog)
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout.addWidget(self.downloadButton, 0, 1, 1, 2)
        self.PrintButton = QtWidgets.QPushButton(Dialog)
        self.PrintButton.setObjectName("PrintButton")
        self.gridLayout.addWidget(self.PrintButton, 0, 3, 1, 1)
        self.resultList = QtWidgets.QListWidget(Dialog)
        self.resultList.setObjectName("resultList")
        self.gridLayout.addWidget(self.resultList, 1, 0, 1, 1)
        self.previewLabel = QtWidgets.QLabel(Dialog)
        self.previewLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewLabel.sizePolicy().hasHeightForWidth())
        self.previewLabel.setSizePolicy(sizePolicy)
        self.previewLabel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.previewLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previewLabel.setAutoFillBackground(False)
        self.previewLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.previewLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.previewLabel.setObjectName("previewLabel")
        self.gridLayout.addWidget(self.previewLabel, 1, 1, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        
        # Professional red & white theme
        Dialog.setStyleSheet("""
            QWidget {
                background: #fff;
                font-family: 'Segoe UI', 'Arial', sans-serif;
            }
            QLabel#label {
                color: #C62828;
                font-weight: bold;
            }
            QLabel {
                color: #333;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid #C62828;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
                color: #222;
            }
            QPushButton {
                background-color: #C62828;
                color: #fff;
                border: none;
                border-radius: 4px;
                padding: 6px 16px;
                font-weight: bold;
                font-size: 12pt;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.downloadButton.setText(_translate("Dialog", "Download"))
        self.PrintButton.setText(_translate("Dialog", "Print"))
        self.previewLabel.setText(_translate("Dialog", "Preview pane"))
import resources_rc
