# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(697, 551)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BVSTDButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BVSTDButton.setFont(font)
        self.BVSTDButton.setObjectName("BVSTDButton")
        self.gridLayout.addWidget(self.BVSTDButton, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.HieuUngButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HieuUngButton.setFont(font)
        self.HieuUngButton.setObjectName("HieuUngButton")
        self.gridLayout.addWidget(self.HieuUngButton, 0, 2, 1, 1)
        self.ThemButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ThemButton.setFont(font)
        self.ThemButton.setObjectName("ThemButton")
        self.gridLayout.addWidget(self.ThemButton, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.TCQCButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TCQCButton.setFont(font)
        self.TCQCButton.setAcceptDrops(True)
        self.TCQCButton.setObjectName("TCQCButton")
        self.gridLayout.addWidget(self.TCQCButton, 5, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 5, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        
                # Professional red & white theme
        Form.setStyleSheet("""
            QWidget {
                background: #fff;
                font-family: 'Segoe UI', 'Arial', sans-serif;
            }
            QLabel#label {
                color: #C62828;
                font-weight: bold;
            }
            QLabel {
                color: #333;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid #C62828;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
                color: #222;
            }
            QPushButton {
                background-color: #C62828;
                color: #fff;
                border: none;
                border-radius: 4px;
                padding: 6px 16px;
                font-weight: bold;
                font-size: 12pt;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.pushButton)
        Form.setTabOrder(self.pushButton, self.HieuUngButton)
        Form.setTabOrder(self.HieuUngButton, self.BVSTDButton)
        Form.setTabOrder(self.BVSTDButton, self.ThemButton)
        Form.setTabOrder(self.ThemButton, self.TCQCButton)
        Form.setTabOrder(self.TCQCButton, self.textEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Colour Master Search Box"))
        self.BVSTDButton.setText(_translate("Form", "Bản vẽ STD"))
        self.pushButton.setText(_translate("Form", "Màu"))
        self.HieuUngButton.setText(_translate("Form", "Hiệu ứng"))
        self.ThemButton.setText(_translate("Form", "Thêm"))
        self.label.setText(_translate("Form", "Thông tin"))
        self.TCQCButton.setText(_translate("Form", "Tiêu Chuẩn QC"))
import resources_rc
