# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timsp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.TimSPButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TimSPButton.setFont(font)
        self.TimSPButton.setObjectName("TimSPButton")
        self.gridLayout.addWidget(self.TimSPButton, 0, 1, 1, 1)
        self.TCKiemtraButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TCKiemtraButton.setFont(font)
        self.TCKiemtraButton.setObjectName("TCKiemtraButton")
        self.gridLayout.addWidget(self.TCKiemtraButton, 0, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        # Professional red & white theme
        MainWindow.setStyleSheet("""
            QWidget {
                background: #fff;
                font-family: 'Segoe UI', 'Arial', sans-serif;
            }
            QLabel#label {
                color: #C62828;
                font-weight: bold;
            }
            QLabel {
                color: #333;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid #C62828;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
                color: #222;
            }
            QPushButton {
                background-color: #C62828;
                color: #fff;
                border: none;
                border-radius: 4px;
                padding: 6px 16px;
                font-weight: bold;
                font-size: 12pt;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.TimSPButton)
        MainWindow.setTabOrder(self.TimSPButton, self.TCKiemtraButton)
        MainWindow.setTabOrder(self.TCKiemtraButton, self.tableView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TimSPButton.setText(_translate("MainWindow", "Tìm kiếm"))
        self.TCKiemtraButton.setText(_translate("MainWindow", "TC Kiểm tra"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
