# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bvstd_window_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(921, 678)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/tlclogo3.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(Dialog)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.OpenButton = QtWidgets.QPushButton(Dialog)
        self.OpenButton.setObjectName("OpenButton")
        self.horizontalLayout.addWidget(self.OpenButton)
        self.downloadButton = QtWidgets.QPushButton(Dialog)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        self.PrintButton = QtWidgets.QPushButton(Dialog)
        self.PrintButton.setObjectName("PrintButton")
        self.horizontalLayout.addWidget(self.PrintButton)
        self.ColorwayButton = QtWidgets.QPushButton(Dialog)
        self.ColorwayButton.setObjectName("ColorwayButton")
        self.horizontalLayout.addWidget(self.ColorwayButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resultList = QtWidgets.QListWidget(Dialog)
        self.resultList.setObjectName("resultList")
        self.horizontalLayout_2.addWidget(self.resultList)
        self.previewLabel = QtWidgets.QLabel(Dialog)
        self.previewLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.previewLabel.setObjectName("previewLabel")
        self.horizontalLayout_2.addWidget(self.previewLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        Dialog.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel#label {
                color: #C62828; /* Strong red for main label */
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #C62828;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.OpenButton.setText(_translate("Dialog", "MỞ"))
        self.downloadButton.setText(_translate("Dialog", "TẢI VỀ"))
        self.PrintButton.setText(_translate("Dialog", "IN"))
        self.ColorwayButton.setText(_translate("Dialog", "RENDER"))
        self.previewLabel.setText(_translate("Dialog", "TextLabel"))
import resources_rc
