# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collection_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1060, 639)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.MILESREDDButton = QtWidgets.QPushButton(Form)
        self.MILESREDDButton.setObjectName("MILESREDDButton")
        self.gridLayout.addWidget(self.MILESREDDButton, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setObjectName("tableView")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setStyleSheet("""
            QTableView {
                background: #fff;
                alternate-background-color: #fbe9e7;
                selection-background-color: #ffcdd2;
                selection-color: #b71c1c;
                font-size: 14px;
                gridline-color: #C62828;
            }
            QHeaderView::section {
                background-color: #C62828;
                color: white;
                font-weight: bold;
                font-size: 14px;
                border: 1px solid #fff;
            }
        """)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.horizontalHeader().setDefaultAlignment(QtCore.Qt.AlignCenter)
        self.tableView.verticalHeader().setDefaultSectionSize(32)
        self.gridLayout.addWidget(self.tableView, 0, 1, 17, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 17, 1)
        self.SUZANNESHARPButton = QtWidgets.QPushButton(Form)
        self.SUZANNESHARPButton.setObjectName("SUZANNESHARPButton")
        self.gridLayout.addWidget(self.SUZANNESHARPButton, 1, 0, 1, 1)
        self.VEEREGRENNEYButton = QtWidgets.QPushButton(Form)
        self.VEEREGRENNEYButton.setObjectName("VEEREGRENNEYButton")
        self.gridLayout.addWidget(self.VEEREGRENNEYButton, 2, 0, 1, 1)
        self.PETERMIKICButton = QtWidgets.QPushButton(Form)
        self.PETERMIKICButton.setObjectName("PETERMIKICButton")
        self.gridLayout.addWidget(self.PETERMIKICButton, 3, 0, 1, 1)
        self.RITAKONIGButton = QtWidgets.QPushButton(Form)
        self.RITAKONIGButton.setObjectName("RITAKONIGButton")
        self.gridLayout.addWidget(self.RITAKONIGButton, 4, 0, 1, 1)
        self.KRBButton = QtWidgets.QPushButton(Form)
        self.KRBButton.setObjectName("KRBButton")
        self.gridLayout.addWidget(self.KRBButton, 5, 0, 1, 1)
        self.JANECHURCHILLButton = QtWidgets.QPushButton(Form)
        self.JANECHURCHILLButton.setObjectName("JANECHURCHILLButton")
        self.gridLayout.addWidget(self.JANECHURCHILLButton, 6, 0, 1, 1)
        self.PENTREATHHALLButton = QtWidgets.QPushButton(Form)
        self.PENTREATHHALLButton.setObjectName("PENTREATHHALLButton")
        self.gridLayout.addWidget(self.PENTREATHHALLButton, 7, 0, 1, 1)
        self.STEVENGAMBRELButton = QtWidgets.QPushButton(Form)
        self.STEVENGAMBRELButton.setObjectName("STEVENGAMBRELButton")
        self.gridLayout.addWidget(self.STEVENGAMBRELButton, 8, 0, 1, 1)
        self.LUKEEDWARDHALLButton = QtWidgets.QPushButton(Form)
        self.LUKEEDWARDHALLButton.setObjectName("LUKEEDWARDHALLButton")
        self.gridLayout.addWidget(self.LUKEEDWARDHALLButton, 9, 0, 1, 1)
        self.JOHNDERIANButton = QtWidgets.QPushButton(Form)
        self.JOHNDERIANButton.setObjectName("JOHNDERIANButton")
        self.gridLayout.addWidget(self.JOHNDERIANButton, 10, 0, 1, 1)
        self.THELACQUERButton = QtWidgets.QPushButton(Form)
        self.THELACQUERButton.setObjectName("THELACQUERButton")
        self.gridLayout.addWidget(self.THELACQUERButton, 11, 0, 1, 1)
        self.SCHUMACHERButton = QtWidgets.QPushButton(Form)
        self.SCHUMACHERButton.setObjectName("SCHUMACHERButton")
        self.gridLayout.addWidget(self.SCHUMACHERButton, 12, 0, 1, 1)
        self.CHRISTOPHERSPITZMILLERButton = QtWidgets.QPushButton(Form)
        self.CHRISTOPHERSPITZMILLERButton.setObjectName("CHRISTOPHERSPITZMILLERButton")
        self.gridLayout.addWidget(self.CHRISTOPHERSPITZMILLERButton, 13, 0, 1, 1)
        self.SALVESENGRAHAMButton = QtWidgets.QPushButton(Form)
        self.SALVESENGRAHAMButton.setObjectName("SALVESENGRAHAMButton")
        self.gridLayout.addWidget(self.SALVESENGRAHAMButton, 14, 0, 1, 1)
        self.JEFFREYBILHUBERButton = QtWidgets.QPushButton(Form)
        self.JEFFREYBILHUBERButton.setObjectName("JEFFREYBILHUBERButton")
        self.gridLayout.addWidget(self.JEFFREYBILHUBERButton, 15, 0, 1, 1)
        self.CAMPBELLREYButton = QtWidgets.QPushButton(Form)
        self.CAMPBELLREYButton.setObjectName("CAMPBELLREYButton")
        self.gridLayout.addWidget(self.CAMPBELLREYButton, 16, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        Form.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel {
                color: #C62828; /* Strong red for main label */
                font-weight: bold;
            }
            QLineEdit, QTextEdit {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #C62828;
                color: white;
                border: 1.5px solid #C62828;
                border-radius: 16px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "COLLECTION WINDOW"))
        self.label_2.setText(_translate("Form", "VIEW COLLECTION"))
        self.MILESREDDButton.setText(_translate("Form", "MILES REDD"))
        self.label.setText(_translate("Form", "Preview"))
        self.SUZANNESHARPButton.setText(_translate("Form", "SUZANNE SHARP"))
        self.VEEREGRENNEYButton.setText(_translate("Form", "VEERE GRENNEY"))
        self.PETERMIKICButton.setText(_translate("Form", "PETER MIKIC"))
        self.RITAKONIGButton.setText(_translate("Form", "RITA KONIG"))
        self.KRBButton.setText(_translate("Form", "KRB"))
        self.JANECHURCHILLButton.setText(_translate("Form", "JANE CHURCHILL"))
        self.PENTREATHHALLButton.setText(_translate("Form", "PENTREATH - HALL"))
        self.STEVENGAMBRELButton.setText(_translate("Form", "STEVEN GAMBREL"))
        self.LUKEEDWARDHALLButton.setText(_translate("Form", "LUKE EDWARD HALL"))
        self.JOHNDERIANButton.setText(_translate("Form", "JOHN DERIAN"))
        self.THELACQUERButton.setText(_translate("Form", "THE LACQUER COMPANY"))
        self.SCHUMACHERButton.setText(_translate("Form", "SCHUMACHER"))
        self.CHRISTOPHERSPITZMILLERButton.setText(_translate("Form", "CHRISTOPHER SPITZMILLER"))
        self.SALVESENGRAHAMButton.setText(_translate("Form", "SALVESEN GRAHAM"))
        self.JEFFREYBILHUBERButton.setText(_translate("Form", "JEFFREY BILHUBER"))
        self.CAMPBELLREYButton.setText(_translate("Form", "CAMPBELL-REY"))
