# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timsp_vi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.TimSPButton = QtWidgets.QPushButton(self.centralwidget)
        self.TimSPButton.setObjectName("TimSPButton")
        self.horizontalLayout.addWidget(self.TimSPButton)
        self.TCKiemtraButton = QtWidgets.QPushButton(self.centralwidget)
        self.TCKiemtraButton.setObjectName("TCKiemtraButton")
        self.horizontalLayout.addWidget(self.TCKiemtraButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setStyleSheet("""
            QWidget {
                background: white;
            }
            QLabel#label {
                color: #C62828; /* Strong red for main label */
                font-weight: bold;
            }
            QLineEdit, QTableView {
                border: 1.5px solid black;
                border-radius: 4px;
                background: #fff;
                padding: 4px;
            }
            QPushButton {
                background-color: #C62828;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 6px 12px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #b71c1c;
            }
        """)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TimSPButton.setText(_translate("MainWindow", "TÌM KIẾM"))
        self.TCKiemtraButton.setText(_translate("MainWindow", "TIÊU CHUẨN KIỂM TRA"))
